Padding footer
itiden/itiden.se pull request #21
Opened 2021-02-09 12:29 UTC by CyrilleKolle

Link to ticket: https://fixa.itiden.se/project/1362/tickets/89
Was to update just contact footer but had to update for other pages since I passed margin as an initial props to page

2021-02-10 12:10 UTC, reekris requested changes
Nice! Som changes needed

2021-02-10 12:10 UTC, reekris commented on components/Layout/Footer.tsx
> +interface IProps {
Can we call this `FooterProps` instead? Makes it clearer

2021-02-10 12:10 UTC, reekris commented on components/Layout/Footer.tsx
> +export const Footer = ({ margin = true }: IProps) => (
Can we rewrite this to `export const Footer: React.FC<FooterProps> = ({ margin = true }) => (`

2021-02-10 12:10 UTC, reekris commented on components/Layout/Page.tsx
> +  margin?: boolean;
Can we set the default value of margin to `true`? Then we don't have to add `margin={true}` to all elements

2021-02-10 12:10 UTC, reekris commented on pages/kontakt.tsx
> +          <ContactsGroup mail location phone />
Should this really be added? I thought we had removed this?

2021-02-10 12:15 UTC, reekris commented on pages/kontakt.tsx
>  const GreenBanner = styled(Hero)`
Maybe change the name of this component since it is now grey?

2021-02-10 12:20 UTC, ricllrstn requested changes
Please also change color of the box and text closest to the footer.

2021-02-11 07:06 UTC, reekris approved these changes
Nice work!

2021-02-11 08:26 UTC, ricllrstn reviewed
Great work!

2021-02-11 08:29 UTC, ricllrstn approved these changes

2021-02-11 08:30 UTC, merged