Update hero hemkontakt
itiden/itiden.se pull request #22
Opened 2021-02-09 13:24 UTC by CyrilleKolle

Link to ticket: https://fixa.itiden.se/project/1362/tickets/78

2021-02-10 14:59 UTC, ricllrstn requested changes
Looks good but change paddin-top from class 48 to 32. (Discussion for later: Do we need a min-height breakpoint that will release from 100vh.)

2021-02-11 06:21 UTC, ricllrstn reviewed
Looking good!

2021-02-11 09:48 UTC, reekris requested changes
Some changes needed

2021-02-11 09:48 UTC, reekris commented on components/Animation/Background.tsx
> +  display:inline;
Remove this file from this PR. It is part of another PR

2021-02-11 09:48 UTC, reekris commented on components/Layout/HeaderWide.tsx
> +    min-height: 560 - 40px;
Instead of writing `560 - 40px` We should write `520px`

2021-02-11 09:48 UTC, reekris commented on components/Layout/HeaderWide.tsx
> +    min-height: 480 - 40px;
Same as above

2021-02-11 09:48 UTC, reekris commented on components/Layout/HeaderWide.tsx
> +    min-height: 820 - 40px;
Same as above

2021-02-11 10:05 UTC, reekris approved these changes
Nice!

2021-02-11 10:07 UTC, ricllrstn approved these changes

2021-02-11 10:07 UTC, merged