Add kocntakt text
itiden/itiden.se pull request #24
Opened 2021-02-10 09:40 UTC by CyrilleKolle

Link to ticket: https://fixa.itiden.se/project/1362/tickets/90

2021-02-10 15:07 UTC, ricllrstn requested changes
Textblock is offset to the left. Should be same as "hem".

2021-02-11 06:35 UTC, ricllrstn reviewed
Nice work!

2021-02-11 13:24 UTC, ricllrstn approved these changes

2021-02-11 15:04 UTC, reekris requested changes
Some minor changes. Also there is a typo in the PR description :)

2021-02-11 15:04 UTC, reekris commented on pages/kontakt.tsx
> +  ${tw`flex flex-col pt-56 md:( pt-0)`}
remove space in `md:( pt-0)`

2021-02-11 15:04 UTC, reekris commented on pages/kontakt.tsx
> +
Remove extra line break

2021-02-11 15:04 UTC, reekris commented on pages/kontakt.tsx
> +const ContactLinkTop = styled.a`
Add line breaks between components

2021-02-11 15:41 UTC, reekris requested changes
- Still some `margin={true}` that can be removed. Check "Files changed" here on github 
- Also fix typo in PR title.

2021-02-11 21:23 UTC, CyrilleKolle commented
I realised "560px-40px" is not the same as 520px so the changes I made that were subsequently merged in to the master didn't show the desired Hero.

2021-02-12 07:03 UTC, ricllrstn approved these changes

2021-02-12 07:41 UTC, reekris requested changes
Make HeaderWide and its children into a reusable component.

- reuse this component on index and kontakt pages

2021-02-15 14:16 UTC, reekris requested changes
Nice! We are really close, just some super minor stuff

2021-02-15 14:16 UTC, reekris commented on components/Layout/HeroContent.tsx
> +import React from 'react';
Could we rename this component to `Hero`? I Think its more concise than `HeroContent`

2021-02-15 14:16 UTC, reekris commented on pages/kontakt.tsx
> +import {HeroContent} from '../components/Layout/HeroContent'
Missing spaces between brackets

2021-02-15 14:16 UTC, reekris commented on pages/kontakt.tsx
> +  ${tw` py-10 bg-gray-700`}
Remove whitespace in beginning of string literal

2021-02-18 07:06 UTC, ricllrstn requested changes
Some minor tweeks:
– Media query for min-height can be set to 610px instead of 780px
– For me it shows ~80px instead of 40px of the next section (Same for "Hem")

2021-02-19 13:39 UTC, ricllrstn submitted a review, later dismissed
Great stuff!

2021-02-19 14:02 UTC, filipengberg requested changes
Some minor stuff

2021-02-19 14:02 UTC, filipengberg commented on components/Layout/HeaderWide.tsx
> +  height: 100vh;
Use tailwind classes instead of hardcoded values

2021-02-19 14:02 UTC, filipengberg commented on components/Layout/HeroContent.tsx
> +  ${tw`w-full mt-1 mb-12 hidden sm:block `};
Remove white space at the end

2021-02-19 14:02 UTC, filipengberg commented on pages/kontakt.tsx
> +  ${tw`max-w-screen-xl px-6 mx-auto items-center mb-32 md:(mt-0 px-5 mb-0) xl:(max-w-screen-lg px-0 mx-auto)`}
mx-auto not needed in xl since it is default

2021-02-19 15:00 UTC, filipengberg approved these changes

2021-02-19 15:01 UTC, merged