Case
itiden/itiden.se pull request #26
Opened 2021-02-15 07:31 UTC by CyrilleKolle

2021-02-15 14:21 UTC, reekris requested changes
Nice work! Some comments

2021-02-15 14:21 UTC, reekris commented on pages/case/[slug].tsx
> +  ${tw`px-0 xs:px-0 sm:px-0 xl:(px-0) lg:(px-0  max-w-full) xl:(max-w-full )`}
Remove whitespace here `xl:(max-w-full )`

2021-02-15 14:21 UTC, reekris commented on pages/case/[slug].tsx
> +
Use tailwind classes here instead of hardcoded values and breakpoints

2021-02-15 14:21 UTC, reekris commented on pages/case/[slug].tsx
> +            `}
Why do we need inline styles here? Can we use a prop instead, or should we change the styling of this component?

2021-02-15 14:21 UTC, reekris commented on pages/case/[slug].tsx
> +          >
Can we remove all the line breaks here? Looks a bit weird to me. Also I think we should remove inline styling. Maybe we could center the content by adding a centered prop to `Content` instead?

2021-02-17 07:54 UTC, filipengberg requested changes
Nice work! Only some minor stuff

2021-02-17 07:54 UTC, filipengberg commented on components/Layout/Footer.tsx
> +  }
Can we convert this to tailwind classes instead of harcodeed @media-queries?

2021-02-17 07:54 UTC, filipengberg commented on pages/case/[slug].tsx
> +  }
Convert to tailwind classes

2021-02-17 07:54 UTC, filipengberg commented on pages/case/[slug].tsx
> +    ${tw`leading-relaxed text-base h-auto w-auto`}
Convert to tailwind classes

2021-02-17 07:54 UTC, filipengberg commented on pages/case/[slug].tsx
> +        >
Can this be written on a single line? Would look nicer I think:
```<MediaWrapper key={index} css={tw`max-w-screen-xxl`}>```

2021-02-17 07:54 UTC, filipengberg commented on pages/case/[slug].tsx
> +          >
Single line for this?

2021-02-17 08:00 UTC, ricllrstn requested changes
Nice! 
Some changes: 
We can simplify some breakpoint by changing the overall x-padding from 40/20/24 to only 24px. That way there is only need for two breakpoints for the footer. It changes from mobile to desktop like it does now and then keep 24px x-padding from the edges until it reaches 1440px where it has its max-width.

The Header changes from mobile like it does today and just like the footer it keeps its x-padding at 24px from the edges. Unlike the footer it will not stop at 1440px. (Maybe the break point need to be 1440 + x-padding x2)

The contact-section should have Kristoffers information and teal as icon color.

2021-02-17 12:08 UTC, filipengberg requested changes
Some changes needed

2021-02-17 12:08 UTC, filipengberg commented on components/Layout/Contact.tsx
> +    }
Remove extra `</>` Wrappers, should not be needed right?

2021-02-17 12:08 UTC, filipengberg commented on components/Layout/Footer.tsx
> +  ${tw` flex flex-col justify-between text-gray-600 px-6 pt-6 pb-5 md:(text-gray-350 px-6 pt-16 pb-10) xl:(px-6 mx-auto) xxl:(max-w-screen-xxl px-6)`}
Remove initial whitespace

2021-02-17 12:08 UTC, filipengberg commented on pages/case/[slug].tsx
> +        >
Same as before, put on one line and skip line breaks. Should be able to write `css` prop as 
```css={tw`max-w-screen-xxl`}```

2021-02-17 12:08 UTC, filipengberg commented on pages/case/[slug].tsx
> +          >
Same here as above

2021-02-17 12:08 UTC, filipengberg commented on tailwind.config.js
> +      yxl: '720px',
Looks like you have added this breakpoint, but its not used anywhere? If so, remove it

2021-02-17 12:59 UTC, ricllrstn requested changes
Nice, some things:
– Images should stop growing att 1440px to align with the footer (since they doesn't have the built in padding the footer does).
– The title "Itiden Lab" behaves a bit wierd at certain break points.
– Icons should be teal color and change to Kristoffers mail and phone number.
– Size of the text "Kontakta Kristoffer Mården om du vill veta mer eller boka tid för möte." should be same as paragraph text (20 or 22px) + Semibold.

2021-02-17 14:40 UTC, ricllrstn requested changes
– Footer, since it has padding need a max width of 1488 (1440+24+24). The text will then align with the images which are 1440 wide at max.

– Some parts of the phone icon are still colored gray.

– Add breakpoint for "Kontakta Kristoffer Mårdén om du vill veta mer eller boka tid för möte." (same as for the paragraph text above.

2021-02-18 12:30 UTC, ricllrstn submitted a review, later dismissed
Excellent :)

2021-02-18 12:47 UTC, filipengberg requested changes
Super close, only megaminor stuff

2021-02-18 12:47 UTC, filipengberg commented on components/Header/Header.tsx
> +  ${tw`flex max-w-screen-xl px-6 pt-6 flex-wrap items-center justify-center flex-col md:(flex-row justify-between items-baseline px-6 pt-5) xl:(max-w-screen-lg px-0 m-auto max-w-full px-6 ) xxl:(max-
Remove trailing whitespace

2021-02-18 12:47 UTC, filipengberg commented on components/Layout/Contact.tsx
> +          `}
Change to css={tw`mt-32`}

2021-02-18 12:47 UTC, filipengberg commented on components/Layout/Footer.tsx
> +  ${tw`flex flex-col justify-between text-gray-600 px-6 pt-6 pb-5 md:(text-gray-350 px-6 pt-16 pb-10) xl:(px-6 mx-auto) axl:(max-w-screen-axl px-6)`}
- Remove px-6 from all breakpoints
- Move max-w-screen-axl to default class
- Remove screen-axl

2021-02-18 12:47 UTC, filipengberg commented on pages/case/[slug].tsx
> +  ${tw`px-0 xs:px-0 sm:px-0 xl:(px-0) lg:(px-0 max-w-full) xl:(max-w-full)`}
Move `max-w-full` out from breakpoints into "default"

2021-02-18 12:47 UTC, filipengberg commented on tailwind.config.js
> +      axl: '1488px',
Remove

2021-02-18 15:14 UTC, filipengberg requested changes
We are close now!

Seems like you have some conflicting styles in your `tw` definitions. Make sure to remove styles that are no longer needed!

2021-02-18 15:14 UTC, filipengberg commented on components/Header/Header.tsx
> +  ${tw`flex max-w-screen-xl px-6 pt-6 flex-wrap items-center justify-center flex-col md:(flex-row justify-between items-baseline px-6 pt-5) xl:(max-w-screen-lg px-0 m-auto max-w-full px-6) xxl:(max-w
`px-6` can be removed from breakpoints since we already have it defined as default
`px-0` can be removed since you overwrite it in the xl breakpoint anyway

2021-02-18 15:14 UTC, filipengberg commented on pages/case/[slug].tsx
> +  ${tw`px-0 xs:px-0 sm:px-0 xl:px-0 max-w-axl max-w-full lg:px-0`}
This looks weird "max-w-axl max-w-full". Only one of theese is needed. If it should be `max-w-full` then you can remove `max-w-axl`

2021-02-18 15:37 UTC, filipengberg requested changes
One last thing :)

2021-02-18 15:37 UTC, filipengberg commented on components/Header/Header.tsx
> +  ${tw`flex max-w-screen-xl px-6 pt-6 flex-wrap items-center justify-center flex-col md:(flex-row justify-between items-baseline pt-5) xl:(max-w-screen-lg m-auto max-w-full) xxl:(max-w-full)`}
`xxl:(max-w-full)` This is not needed since you already set `max-w-full` in the `xl` breakpoint

2021-02-18 15:48 UTC, filipengberg approved these changes
🥳

2021-02-18 15:51 UTC, ricllrstn approved these changes

2021-02-18 17:32 UTC, merged