Om
itiden/itiden.se pull request #27
Opened 2021-02-19 15:08 UTC by CyrilleKolle

2021-02-22 12:14 UTC, ricllrstn requested changes
Nice!
Some changes:
– Size/ratio of hero-image should be the same as Specific-case even for mobile (will most likely export a new image but old one will do for now)
– Space below hero-image on mobile
– Space above and below the three image are too big on mobile and smaller desktop
– Space above footer missing
– Add button "Våra tjänster" to section about app, webb and system
– Sizes for p in in "Våra tjänster"-section to mimic p in textfield above in "Kom och hälsa på oss" etc
– Change to hej@itiden.se and 0709-59 70 08 
– Some additional space to the right margin seem to have been added to sizes below 768px

2021-02-23 07:03 UTC, ricllrstn requested changes
Mobile:
– Space between hero and text
– Space between images (with imagetext)
– Space between last image and text
– Space between last text and "Våra tjänster"-section (16+80=96 but should be 16+64=80)
– Space below button
– Mobile hero image size

Desktop ~1440-breakpoint and below
– Space between last text and "Våra tjänster"-section (Should be 80 but is 16+96)
– Space above and below button should be 80 in total

Desktop ~1440-breakpoint and above
– Space between hero-image and text should be 96
– Space above and below the three images should be 96

Våra tjänster section:
– Desktop ~1440-breakpoint and below: Adjust badding between
– Desktop ~1440-breakpoint and above: Adjust padding between and overall width

2021-02-24 06:46 UTC, ricllrstn requested changes
Almost!
– I realised that the larger breakpoint should take affect at 1920 (like Figma) and not ~1440 as I wrongfully wrote in my previous review.
– Hero-image size for mobile should be the same as for the hero on case-specific (taler then now, do you need a new image before that can take effect?)
– Våra tjänster section is not centered at larger breakpoint and the spacing around the button is a little off. It seems to be inconsequent coded between sizes, maybe better to leave that for Filips review?

2021-02-24 11:35 UTC, ricllrstn requested changes
Extremely close now, all i can find is the space between the first paragraph and the terass-image on mobile is a bit too big :)

2021-02-24 12:24 UTC, ricllrstn approved these changes
Great stuff! 🔥🔥🔥🔥🔥🔥🔥

2021-02-24 16:37 UTC, filipengberg requested changes
Good stuff!
Mostly minor stuff and some questions. Meybe we can go through the questions together on Discord?

2021-02-24 16:37 UTC, filipengberg commented on components/AboutIcons/IconsGroup.tsx
> +  ${tw`items-start sm:items-center pb-24 flex flex-col lg:w-1/3 xxl:(py-0 w-25)`}
Should it be `pb-0` here instead of `py-0`? Since we override the default class of `pb-24`

2021-02-24 16:37 UTC, filipengberg commented on components/AboutIcons/IconsGroup.tsx
> +    max-width: 400px;
Replace hard-coded values with tailwind classes!

2021-02-24 16:37 UTC, filipengberg commented on pages/om.tsx
> +  ${tw`w-full mb-20 odd:my-10 last:(mb-0 -mt-10) md:(mb-0 odd:my-auto last:mt-auto)`}
How come `odd` is used?

2021-02-24 16:37 UTC, filipengberg commented on pages/om.tsx
> +`;
Add line breaks between nested rules. `& p` etc

2021-02-24 16:37 UTC, filipengberg commented on pages/om.tsx
>  const ImageWrapperDesktop = styled.div`
I saw that `ImageWrapperDesktop`, `ImageWrapperMobile`, `ImageWrapper` and maybe others are also defined in  `pages/jobb-webbutvecklare-dotnet.tsx`. Maybe we could move these to reusable components?

2021-02-24 16:37 UTC, filipengberg commented on pages/om.tsx
> +  ${tw`justify-center flex flex-col mb-6 -mt-2 -mt-5 md:(mb-20) xxl:(my-0 pt-20 pb-24)`}
Why do we need negative margin here?

2021-02-24 16:37 UTC, filipengberg commented on pages/om.tsx
> +            <H3 css={`${tw`mt-10`}`}>
Remove unneeded `${}` around `tw`

2021-02-24 16:37 UTC, filipengberg commented on pages/om.tsx
> +            <H3 css={`${tw`mt-10`}`}>
Remove unneeded `${}` here as well!

2021-02-26 10:52 UTC, filipengberg commented on pages/om.tsx
> +  ${tw`justify-center flex flex-col mb-6 -mt-2 -mt-5 md:(mb-20) xxl:(my-0 pt-20 pb-24)`}
Remove -mt and make lesser margin on components before this one instead

2021-02-26 10:54 UTC, filipengberg requested changes
Some minor fixes that we discussed on Discord!

2021-02-26 23:44 UTC, filipengberg requested changes
Seems like something happened in your last commit. There is a lot of new files added under a .history folder. What happened? I think you should do a hard reset to the commit before this one and apply the changes again.

2021-03-04 15:58 UTC, andreasbergqvist requested changes
Det finns några props som jag tycker strular till det lite i mitt huvud =)

Tex:
```
{props.phone && (
        <>
          <ContactBox>
            <ContactLink href="tel:0709-597008">
              <IconWrapper>
                <PhoneIcon />
              </IconWrapper>
              <LiteIconWrapper>
                <PhoneLiteIcon />
              </LiteIconWrapper>
              <ContactInfo>{props.telephone}</ContactInfo>
            </ContactLink>
          </ContactBox>
        </>
      )}
```
   
Märkligt med både phone och telephone.
Dessutom är href:en till hårdkodat nummer?

Aningen så borde if:en vara om telephone är != null, eller också tycker jag att boolean propen skall vara tex "showPhone" (och då kanske telephone borde vara bara phone)

2021-03-05 09:15 UTC, merged